# Generated by Django 4.2.15 on 2025-08-23 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_user_task_user_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_task',
            new_name='user',
        ),
    ]
